import { library } from "@fortawesome/fontawesome-svg-core"
import {
    faHatWizard,
    faRightFromBracket,
    faTimes,
    faXmark,
    faUsers,
    faLayerGroup,
    faMoneyBillTrendUp,
    faHandHoldingDollar,
    faGear,
    faBookOpen,
    faCode,
    faArrowRightFromBracket,
    faCaretLeft,
    faCaretRight,
    faClose,
    faPlus,
    faEnvelope,
    faCheck,
    faExclamation,
    faTriangleExclamation,
    faCircleExclamation,
    faCalendar,
    faArrowRight,
    faPenToSquare,
    faChevronLeft,
    faInfo,
    faStar,
    faStarHalfAlt,
} from "@fortawesome/free-solid-svg-icons"
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add([
    faHatWizard,
    faRightFromBracket,
    faTimes,
    faXmark,
    faUsers,
    faLayerGroup,
    faMoneyBillTrendUp,
    faHandHoldingDollar,
    faGear,
    faBookOpen,
    faCode,
    faArrowRightFromBracket,
    faCaretLeft,
    faCaretRight,
    faPlus,
    faClose,
    faEnvelope,
    faCheck,
    faExclamation,
    faTriangleExclamation,
    faCircleExclamation,
    faCalendar,
    faArrowRight,
    faPenToSquare,
    faChevronLeft,
    faInfo,
    faStar,
    faStarHalfAlt,
])

export default FontAwesomeIcon
